//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MVCCrystalReport
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class efarmingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new efarmingEntities object using the connection string found in the 'efarmingEntities' section of the application configuration file.
        /// </summary>
        public efarmingEntities() : base("name=efarmingEntities", "efarmingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new efarmingEntities object.
        /// </summary>
        public efarmingEntities(string connectionString) : base(connectionString, "efarmingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new efarmingEntities object.
        /// </summary>
        public efarmingEntities(EntityConnection connection) : base(connection, "efarmingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Investment> Investments
        {
            get
            {
                if ((_Investments == null))
                {
                    _Investments = base.CreateObjectSet<Investment>("Investments");
                }
                return _Investments;
            }
        }
        private ObjectSet<Investment> _Investments;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Investments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvestments(Investment investment)
        {
            base.AddObject("Investments", investment);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="efarmingModel", Name="Investment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Investment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Investment object.
        /// </summary>
        /// <param name="investmentNo">Initial value of the InvestmentNo property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="investmentAmount">Initial value of the InvestmentAmount property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Investment CreateInvestment(global::System.Int64 investmentNo, global::System.String firstName, global::System.String lastName, global::System.Decimal investmentAmount, global::System.Boolean isActive)
        {
            Investment investment = new Investment();
            investment.InvestmentNo = investmentNo;
            investment.FirstName = firstName;
            investment.LastName = lastName;
            investment.InvestmentAmount = investmentAmount;
            investment.IsActive = isActive;
            return investment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 InvestmentNo
        {
            get
            {
                return _InvestmentNo;
            }
            set
            {
                if (_InvestmentNo != value)
                {
                    OnInvestmentNoChanging(value);
                    ReportPropertyChanging("InvestmentNo");
                    _InvestmentNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InvestmentNo");
                    OnInvestmentNoChanged();
                }
            }
        }
        private global::System.Int64 _InvestmentNo;
        partial void OnInvestmentNoChanging(global::System.Int64 value);
        partial void OnInvestmentNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MobileNo
        {
            get
            {
                return _MobileNo;
            }
            set
            {
                OnMobileNoChanging(value);
                ReportPropertyChanging("MobileNo");
                _MobileNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MobileNo");
                OnMobileNoChanged();
            }
        }
        private Nullable<global::System.Int32> _MobileNo;
        partial void OnMobileNoChanging(Nullable<global::System.Int32> value);
        partial void OnMobileNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Landline
        {
            get
            {
                return _Landline;
            }
            set
            {
                OnLandlineChanging(value);
                ReportPropertyChanging("Landline");
                _Landline = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Landline");
                OnLandlineChanged();
            }
        }
        private Nullable<global::System.Int32> _Landline;
        partial void OnLandlineChanging(Nullable<global::System.Int32> value);
        partial void OnLandlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OtherNo
        {
            get
            {
                return _OtherNo;
            }
            set
            {
                OnOtherNoChanging(value);
                ReportPropertyChanging("OtherNo");
                _OtherNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OtherNo");
                OnOtherNoChanged();
            }
        }
        private Nullable<global::System.Int32> _OtherNo;
        partial void OnOtherNoChanging(Nullable<global::System.Int32> value);
        partial void OnOtherNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal InvestmentAmount
        {
            get
            {
                return _InvestmentAmount;
            }
            set
            {
                OnInvestmentAmountChanging(value);
                ReportPropertyChanging("InvestmentAmount");
                _InvestmentAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvestmentAmount");
                OnInvestmentAmountChanged();
            }
        }
        private global::System.Decimal _InvestmentAmount;
        partial void OnInvestmentAmountChanging(global::System.Decimal value);
        partial void OnInvestmentAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> InvestmentDate
        {
            get
            {
                return _InvestmentDate;
            }
            set
            {
                OnInvestmentDateChanging(value);
                ReportPropertyChanging("InvestmentDate");
                _InvestmentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvestmentDate");
                OnInvestmentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _InvestmentDate;
        partial void OnInvestmentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnInvestmentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion

    
    }

    #endregion

    
}
